

main: main.c process.c point.c ADC.c match.c process.h ADC.h includes.h dsp.h dsp.c fft.c fft.h point.h match.c match.h type.h mfcc.h mfcc.c
	gcc -Wall -lm main.c process.c point.c ADC.c match.c  dsp.c mfcc.c fft.c -o main

clean:
	rm -f main
